/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mvc.vista;

/**
 *
 * @author ACER
 */
public class VentanaClinica extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaClinica.class.getName());

    /**
     * Creates new form VentanaClinica
     */
    public VentanaClinica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        construirVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void construirVista() {
    setTitle("Panel Clínico");
    getContentPane().setBackground(new java.awt.Color(102, 153, 255));
    setLayout(new java.awt.BorderLayout());

    javax.swing.JPanel panelTitulo = new javax.swing.JPanel();
    panelTitulo.setBackground(new java.awt.Color(255, 255, 255));
    panelTitulo.setLayout(new java.awt.BorderLayout());

    javax.swing.JLabel lblTitulo = new javax.swing.JLabel("Panel Clínico");
    lblTitulo.setFont(new java.awt.Font("Georgia", 2, 24));

    jLabel2 = new javax.swing.JLabel("Bienvenido/a, Dr/Dra.");
    jLabel2.setFont(new java.awt.Font("Georgia", 0, 14));
    jLabel2.setForeground(new java.awt.Color(0, 0, 102));

    javax.swing.JPanel barraAzul = new javax.swing.JPanel();
    barraAzul.setBackground(new java.awt.Color(0, 0, 51));
    barraAzul.setPreferredSize(new java.awt.Dimension(584, 11));

    javax.swing.JPanel panelTexto = new javax.swing.JPanel();
    panelTexto.setBackground(new java.awt.Color(255, 255, 255));
    panelTexto.setLayout(new javax.swing.BoxLayout(panelTexto, javax.swing.BoxLayout.Y_AXIS));
    panelTexto.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 91, 0, 0));
    panelTexto.add(lblTitulo);
    panelTexto.add(jLabel2);
    panelTitulo.add(panelTexto, java.awt.BorderLayout.CENTER);
    panelTitulo.add(barraAzul, java.awt.BorderLayout.SOUTH);

    javax.swing.JPanel panelBotones = new javax.swing.JPanel();
    panelBotones.setBackground(new java.awt.Color(102, 153, 255));
    panelBotones.setLayout(new java.awt.GridBagLayout());
    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    gbc.gridx = 0;
    gbc.insets = new java.awt.Insets(14, 0, 14, 0);
    gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

    botonPacientes = new javax.swing.JButton("Mis Pacientes");
    botonPacientes.setBackground(new java.awt.Color(0, 0, 102));
    botonPacientes.setFont(new java.awt.Font("Calisto MT", 1, 22));
    botonPacientes.setForeground(new java.awt.Color(255, 204, 255));
    botonPacientes.setPreferredSize(new java.awt.Dimension(266, 80));

    botonTratamiento = new javax.swing.JButton("Asignar Tratamiento");
    botonTratamiento.setBackground(new java.awt.Color(0, 0, 102));
    botonTratamiento.setFont(new java.awt.Font("Calisto MT", 1, 22));
    botonTratamiento.setForeground(new java.awt.Color(255, 204, 255));
    botonTratamiento.setPreferredSize(new java.awt.Dimension(266, 80));

    botonFactura = new javax.swing.JButton("Generar Factura");
    botonFactura.setBackground(new java.awt.Color(0, 0, 102));
    botonFactura.setFont(new java.awt.Font("Calisto MT", 1, 22));
    botonFactura.setForeground(new java.awt.Color(255, 204, 255));
    botonFactura.setPreferredSize(new java.awt.Dimension(266, 80));

    gbc.gridy = 0; panelBotones.add(botonPacientes, gbc);
    gbc.gridy = 1; panelBotones.add(botonTratamiento, gbc);
    gbc.gridy = 2; panelBotones.add(botonFactura, gbc);

    add(panelTitulo, java.awt.BorderLayout.NORTH);
    add(panelBotones, java.awt.BorderLayout.CENTER);
    pack();
}

    public void setNombreMedico(String nombre) {
        jLabel2.setText("Bienvenido/a, Dr/Dra. " + nombre);
    }

    public void conectControlador(mvc.controlador.ControladorClinico controlador) {
        botonPacientes.addActionListener(e -> controlador.abrirPacientes());
        botonTratamiento.addActionListener(e -> controlador.abrirTratamiento());
        botonFactura.addActionListener(e -> controlador.abrirFactura());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaClinica dialog = new VentanaClinica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private javax.swing.JButton botonPacientes;
    private javax.swing.JButton botonTratamiento;
    private javax.swing.JButton botonFactura;
    private javax.swing.JLabel jLabel2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
