/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mvc.vista;

/**
 *
 * @author ACER
 */
public class VentanaListaPacientesEnfermero extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaListaPacientesEnfermero.class.getName());

    /**
     * Creates new form VentanaListaPacientesEnfermero
     */
    public VentanaListaPacientesEnfermero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        construirVista();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaListaPacientesEnfermero dialog = new VentanaListaPacientesEnfermero(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     private javax.swing.JTable tablaPacientes;
     private javax.swing.table.DefaultTableModel modeloTabla;
     private javax.swing.JScrollPane jScrollPane1;

     public javax.swing.JTable getTablaPacientes() {
        return tablaPacientes;
    }

     public javax.swing.table.DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }
     public javax.swing.JButton getBotonVerDosis() {
     return botonVerDosis;
    }

   private void construirVista() {
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaPacientes = new javax.swing.JTable();
    botonVerDosis = new javax.swing.JButton();
    
    modeloTabla = new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"ID", "Nombre", "Médico"}
    ) {
        boolean[] canEdit = new boolean [] {false, false, false};
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };
    
    tablaPacientes.setModel(modeloTabla);
    jScrollPane1.setViewportView(tablaPacientes);
    
    botonVerDosis.setBackground(new java.awt.Color(0, 0, 102));
    botonVerDosis.setFont(new java.awt.Font("Calisto MT", 1, 18));
    botonVerDosis.setForeground(new java.awt.Color(255, 204, 255));
    botonVerDosis.setText("Ver Dosis");
    
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
    .addGroup(layout.createSequentialGroup()
    .addGap(180, 180, 180)
    .addComponent(botonVerDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(180, 180, 180))
    );
    layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(20, 20, 20)
    .addComponent(botonVerDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(20, 20, 20))
    );
    
    pack();
    setSize(579, 460);
}
    private javax.swing.JButton botonVerDosis;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
