/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mvc.vista;

/**
 *
 * @author ACER
 */
public class VentanaDetallesDosis extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaDetallesDosis.class.getName());

    /**
     * Creates new form VentanaDetallesDosis
     */
        public VentanaDetallesDosis(java.awt.Dialog parent, boolean modal, mvc.modelo.Paciente paciente, mvc.modelo.GestorHospital gestor) {
         super(parent, modal);
         this.paciente = paciente;
         this.gestor = gestor;
         initComponents();
         construirVista();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaDetallesDosis dialog = new VentanaDetallesDosis(new javax.swing.JDialog(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void construirVista() {
    checkboxes = new java.util.ArrayList<>();
    
    jLabel1 = new javax.swing.JLabel("Tratamientos de: " + paciente.getNombre());
    jLabel1.setFont(new java.awt.Font("Georgia", 2, 18));
    jLabel1.setForeground(new java.awt.Color(0, 0, 102));

    panelDosis = new javax.swing.JPanel();
    panelDosis.setLayout(new javax.swing.BoxLayout(panelDosis, javax.swing.BoxLayout.Y_AXIS));
    panelDosis.setBackground(new java.awt.Color(204, 255, 255));

    java.util.ArrayList<mvc.modelo.AATratamiento> tratamientos = paciente.getListaTratamientos();
    if (tratamientos.isEmpty()) {
        panelDosis.add(new javax.swing.JLabel("El paciente no tiene tratamientos asignados."));
    } else {
     for (mvc.modelo.AATratamiento t : tratamientos) {
     javax.swing.JLabel labelTrat = new javax.swing.JLabel("-- " + t.getNomTrat() + " --");
     labelTrat.setFont(new java.awt.Font("Calisto MT", 1, 16));
     labelTrat.setForeground(new java.awt.Color(0, 0, 102));
     panelDosis.add(labelTrat);

     int total = 1;
     String prefijo = "Completado";
            
     int completados = gestor.getProgresoDosis().getOrDefault(Math.abs((paciente.getIdP() + "_" + t.getNomTrat() + "_" + t.getTDTratamiento()).hashCode()), 0);

     if (t instanceof mvc.modelo.AMedicacion) {
        total = ((mvc.modelo.AMedicacion) t).getDiasTratamiento();
        prefijo = "Día";
         } else if (t instanceof mvc.modelo.ATerapia) {
           total = ((mvc.modelo.ATerapia) t).getCantidadSemanas();
            prefijo = "Semana";
            }
            if (t instanceof mvc.modelo.AMedicacion) {
            total = ((mvc.modelo.AMedicacion) t).getDiasTratamiento();
            prefijo = "Día";
        } else if (t instanceof mvc.modelo.ATerapia) {
            total = ((mvc.modelo.ATerapia) t).getCantidadSemanas();
            prefijo = "Semana";
        } else if (t instanceof mvc.modelo.ACirugia) {
            String tipoCirugia = ((mvc.modelo.ACirugia) t).getTipoCirugia();
            javax.swing.JCheckBox cb = new javax.swing.JCheckBox("Cirugía: " + tipoCirugia);
            cb.setFont(new java.awt.Font("Calisto MT", 0, 15));
            cb.setBackground(new java.awt.Color(204, 255, 255));
            if (completados >= 1) {
                cb.setSelected(true);
                cb.setEnabled(false);
            }
            checkboxes.add(cb);
            panelDosis.add(cb);
            panelDosis.add(new javax.swing.JSeparator());
            continue;
        }

        for (int i = 1; i <= total; i++) {
            javax.swing.JCheckBox cb = new javax.swing.JCheckBox(prefijo + " " + i);
            cb.setFont(new java.awt.Font("Calisto MT", 0, 15));
            cb.setBackground(new java.awt.Color(204, 255, 255));
            if (i <= completados) {
             cb.setSelected(true);
             cb.setEnabled(false);
             }
             checkboxes.add(cb);
             panelDosis.add(cb);
             }
             panelDosis.add(new javax.swing.JSeparator());
        }
    }

    jScrollPane1 = new javax.swing.JScrollPane(panelDosis);

    botonGuardar = new javax.swing.JButton("Guardar");
    botonGuardar.setBackground(new java.awt.Color(0, 0, 102));
    botonGuardar.setFont(new java.awt.Font("Calisto MT", 1, 18));
    botonGuardar.setForeground(new java.awt.Color(255, 204, 255));
    botonGuardar.addActionListener(e -> guardarDosis());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel1)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
        .addGap(120, 120, 120)
        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(20, 20, 20))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel1)
        .addGap(10, 10, 10)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20))
    );

    setSize(500, 480);
}
   
private void guardarDosis() {
    java.util.ArrayList<mvc.modelo.AATratamiento> tratamientos = paciente.getListaTratamientos();
    java.util.ArrayList<mvc.modelo.AATratamiento> completados = new java.util.ArrayList<>();
    
    int checkIndex = 0;
    for (mvc.modelo.AATratamiento t : tratamientos) {
    int total = 1;
    if (t instanceof mvc.modelo.AMedicacion) {
        total = ((mvc.modelo.AMedicacion) t).getDiasTratamiento();
    } else if (t instanceof mvc.modelo.ATerapia) {
            total = ((mvc.modelo.ATerapia) t).getCantidadSemanas();
        }

     int marcados = 0;
     for (int i = 0; i < total; i++) {
     if (checkIndex < checkboxes.size() && checkboxes.get(checkIndex).isSelected()) {
     marcados++;
     }
     checkIndex++;
     }

     gestor.getProgresoDosis().put(Math.abs((paciente.getIdP() + "_" + t.getNomTrat() + "_" + t.getTDTratamiento()).hashCode()), marcados);
     if (marcados >= total) {
      completados.add(t);
      }
    }

    for (mvc.modelo.AATratamiento t : completados) {
        paciente.finalizarTratamiento(t);
    }

    gestor.GuardarDatos();

    if (paciente.getListaTratamientos().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, paciente.getNombre() + " finalizó su tratamiento.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Progreso guardado correctamente.");
    }
    dispose();
}
 private mvc.modelo.Paciente paciente;
 private mvc.modelo.GestorHospital gestor;
 private javax.swing.JPanel panelDosis;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JButton botonGuardar;
 private javax.swing.JLabel jLabel1;
 private java.util.ArrayList<javax.swing.JCheckBox> checkboxes;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
