/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mvc.vista;

/**
 *
 * @author ACER
 */
public class VentanaListaPacients extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaListaPacients.class.getName());

    /**
     * Creates new form VentanaListaPacients
     */
    public VentanaListaPacients(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        construirVista();
        setLocationRelativeTo(null);
    }
    
            private void construirVista() {
            setTitle("Mis Pacientes");
            setSize(600, 530);
            setLocationRelativeTo(null);
            setLayout(new java.awt.BorderLayout());

            javax.swing.JPanel panelTitulo = new javax.swing.JPanel(new java.awt.BorderLayout());
            panelTitulo.setBackground(new java.awt.Color(255, 255, 255));

            javax.swing.JPanel panelTexto = new javax.swing.JPanel();
            panelTexto.setBackground(new java.awt.Color(255, 255, 255));
            panelTexto.setLayout(new javax.swing.BoxLayout(panelTexto, javax.swing.BoxLayout.Y_AXIS));
            panelTexto.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 91, 0, 0));

            javax.swing.JLabel lblTitulo = new javax.swing.JLabel("Mis Pacientes");
            lblTitulo.setFont(new java.awt.Font("Georgia", 2, 24));

            javax.swing.JPanel barraAzul = new javax.swing.JPanel();
            barraAzul.setBackground(new java.awt.Color(0, 0, 51));
            barraAzul.setPreferredSize(new java.awt.Dimension(600, 11));

            panelTexto.add(lblTitulo);
            panelTitulo.add(panelTexto, java.awt.BorderLayout.CENTER);
            panelTitulo.add(barraAzul, java.awt.BorderLayout.SOUTH);
            
            botonAlta = new javax.swing.JButton("Dar de Alta");
            botonAlta.setBackground(new java.awt.Color(102, 0, 0));
            botonAlta.setFont(new java.awt.Font("Calisto MT", 1, 18));
            botonAlta.setForeground(new java.awt.Color(255, 255, 255));
            botonAlta.setPreferredSize(new java.awt.Dimension(200, 45));

            javax.swing.JPanel panelBoton = new javax.swing.JPanel();
            panelBoton.setBackground(new java.awt.Color(102, 153, 255));
            panelBoton.add(botonAlta);

            String[] columnas = {"ID", "Nombre", "Estado", "Tratamiento"};
            modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0);
            tablaPacientes = new javax.swing.JTable(modeloTabla);
            tablaPacientes.setFont(new java.awt.Font("Calisto MT", 0, 14));
            tablaPacientes.setRowHeight(30);
            tablaPacientes.getTableHeader().setBackground(new java.awt.Color(0, 0, 102));
            tablaPacientes.getTableHeader().setForeground(new java.awt.Color(0, 0, 51));
            tablaPacientes.getTableHeader().setFont(new java.awt.Font("Calisto MT", 1, 14));

            javax.swing.JScrollPane scrollTabla = new javax.swing.JScrollPane(tablaPacientes);
            scrollTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));

            javax.swing.JPanel panelCentral = new javax.swing.JPanel(new java.awt.BorderLayout());
            panelCentral.setBackground(new java.awt.Color(102, 153, 255));
            panelCentral.add(scrollTabla, java.awt.BorderLayout.CENTER);

            add(panelTitulo, java.awt.BorderLayout.NORTH);
            add(panelCentral, java.awt.BorderLayout.CENTER);
            add(panelBoton, java.awt.BorderLayout.SOUTH);
        }

        public javax.swing.table.DefaultTableModel getModeloTabla() { return modeloTabla; }
        public javax.swing.JTable getTablaPacientes() { return tablaPacientes; }
        public javax.swing.JButton getBotonAlta() { return botonAlta; }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaListaPacients dialog = new VentanaListaPacients(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
                
    private javax.swing.JTable tablaPacientes;
    private javax.swing.table.DefaultTableModel modeloTabla;
    private javax.swing.JButton botonAlta;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
